backend:
  name: git-gateway
  branch: main

# Activation de la langue française
locale: 'fr'

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Articles de Blog"
    folder: "_posts/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Catégorie", name: "tag", widget: "string" }
      - { label: "Résumé", name: "desc", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "flyers"
    label: "Flyers & Promotions"
    folder: "_posts/flyers"
    create: true
    slug: "{{slug}}"
    # Version ultra-simplifiée :
    fields:
      - { label: "Nom de la promotion (ex: Flyer Juin)", name: "title", widget: "string" }
      - { label: "Image du flyer", name: "image", widget: "image" }