backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Articles de Blog"
    folder: "content/blog" # Le CMS crée un fichier par article ici
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Titre de l'article", name: "title", widget: "string" }
      - { label: "Description courte", name: "desc", widget: "string" }
      - { label: "Image de couverture", name: "img", widget: "image" }
      - { label: "Contenu de l'article", name: "content", widget: "markdown" }