backend:
  name: github
  repo: camelDOUMTSOP/le-site-de-Dr-fouenang-propre-sans-CMS
  branch: main
  base_url: https://drpatrickfouenang.com
  auth_endpoint: /oauth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Articles de Blog"
    folder: "_posts/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Catégorie", name: "tag", widget: "string" }
      - { label: "Résumé", name: "desc", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "flyers"
    label: "Flyers & Promotions"
    folder: "_posts/flyers"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image du flyer", name: "image", widget: "image" }
      - { label: "Description", name: "desc", widget: "string" }